version: '3.8'

services:
  db:
    container_name: mongodb
    image: mongo:6.0.8
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
    volumes:
      - type: bind
        source: data/db
        target: /data/db
        bind:
          create_host_path: true
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    command: mongod --port ${DB_PORT}
    restart: always

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    networks:
      - backend
    volumes:
      - type: bind
        source: data/me
        target: /data/me
        bind:
          create_host_path: true
    environment:
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
      VCAP_APP_PORT: ${MONGO_EXPRESS_PORT}
    restart: unless-stopped

  api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    networks:
      - backend
    volumes:
      - .:/app
    env_file:
      - .env
    user: node:node
    ports:
      - ${PORT}:${PORT}
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    command: npm start
    restart: always

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge

volumes:
  data:
    name: mongo
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind,nolock,soft,rw'
      device: './data'
