version: '3.8'

services:
  db:
    container_name: ${DB_HOST}
    restart: always
    image: mongo:6.0.8
    ports:
      - ${DB_PORT}:27017
    networks:
      - backend
    volumes:
      - type: bind
        source: data/db
        target: /data/db
        bind:
          create_host_path: true
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    networks:
      - backend
    volumes:
      - type: bind
        source: data/me
        target: /data/me
        bind:
          create_host_path: true
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://db:${DB_PORT}/

  api:
    depends_on:
      - db
    container_name: api
    restart: always
    build: .
    user: node:node
    ports:
      - ${PORT}:3000
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge

volumes:
  data:
    name: mongo
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind,nolock,soft,rw'
      device: './data'
